//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Cursed
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ряд.
    /// </summary>
    // *** Start programmer edit section *** (Ряд CustomAttributes)

    // *** End programmer edit section *** (Ряд CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РядE", new string[] {
            "НомерРяда as \'Номер ряда\'"})]
    [View("РядL", new string[] {
            "НомерРяда as \'Номер ряда\'"})]
    public class Ряд : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерРяда;
        
        // *** Start programmer edit section *** (Ряд CustomMembers)

        // *** End programmer edit section *** (Ряд CustomMembers)

        
        /// <summary>
        /// НомерРяда.
        /// </summary>
        // *** Start programmer edit section *** (Ряд.НомерРяда CustomAttributes)

        // *** End programmer edit section *** (Ряд.НомерРяда CustomAttributes)
        public virtual int НомерРяда
        {
            get
            {
                // *** Start programmer edit section *** (Ряд.НомерРяда Get start)

                // *** End programmer edit section *** (Ряд.НомерРяда Get start)
                int result = this.fНомерРяда;
                // *** Start programmer edit section *** (Ряд.НомерРяда Get end)

                // *** End programmer edit section *** (Ряд.НомерРяда Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ряд.НомерРяда Set start)

                // *** End programmer edit section *** (Ряд.НомерРяда Set start)
                this.fНомерРяда = value;
                // *** Start programmer edit section *** (Ряд.НомерРяда Set end)

                // *** End programmer edit section *** (Ряд.НомерРяда Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РядE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РядE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РядE", typeof(IIS.Cursed.Ряд));
                }
            }
            
            /// <summary>
            /// "РядL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РядL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РядL", typeof(IIS.Cursed.Ряд));
                }
            }
        }
    }
}
