//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Cursed
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Этаж.
    /// </summary>
    // *** Start programmer edit section *** (Этаж CustomAttributes)

    // *** End programmer edit section *** (Этаж CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЭтажE", new string[] {
            "НомерЭтажа as \'Номер этажа\'",
            "Ряд as \'Ряд\'",
            "Ряд.НомерРяда as \'Номер ряда\'"}, Hidden=new string[] {
            "Ряд.НомерРяда"})]
    [MasterViewDefineAttribute("ЭтажE", "Ряд", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерРяда")]
    [View("ЭтажL", new string[] {
            "НомерЭтажа as \'Номер этажа\'",
            "Ряд.НомерРяда as \'Номер ряда\'"})]
    public class Этаж : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЭтажа;
        
        private IIS.Cursed.Ряд fРяд;
        
        // *** Start programmer edit section *** (Этаж CustomMembers)

        // *** End programmer edit section *** (Этаж CustomMembers)

        
        /// <summary>
        /// НомерЭтажа.
        /// </summary>
        // *** Start programmer edit section *** (Этаж.НомерЭтажа CustomAttributes)

        // *** End programmer edit section *** (Этаж.НомерЭтажа CustomAttributes)
        public virtual int НомерЭтажа
        {
            get
            {
                // *** Start programmer edit section *** (Этаж.НомерЭтажа Get start)

                // *** End programmer edit section *** (Этаж.НомерЭтажа Get start)
                int result = this.fНомерЭтажа;
                // *** Start programmer edit section *** (Этаж.НомерЭтажа Get end)

                // *** End programmer edit section *** (Этаж.НомерЭтажа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Этаж.НомерЭтажа Set start)

                // *** End programmer edit section *** (Этаж.НомерЭтажа Set start)
                this.fНомерЭтажа = value;
                // *** Start programmer edit section *** (Этаж.НомерЭтажа Set end)

                // *** End programmer edit section *** (Этаж.НомерЭтажа Set end)
            }
        }
        
        /// <summary>
        /// Этаж.
        /// </summary>
        // *** Start programmer edit section *** (Этаж.Ряд CustomAttributes)

        // *** End programmer edit section *** (Этаж.Ряд CustomAttributes)
        [PropertyStorage(new string[] {
                "Ряд"})]
        [NotNull()]
        public virtual IIS.Cursed.Ряд Ряд
        {
            get
            {
                // *** Start programmer edit section *** (Этаж.Ряд Get start)

                // *** End programmer edit section *** (Этаж.Ряд Get start)
                IIS.Cursed.Ряд result = this.fРяд;
                // *** Start programmer edit section *** (Этаж.Ряд Get end)

                // *** End programmer edit section *** (Этаж.Ряд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Этаж.Ряд Set start)

                // *** End programmer edit section *** (Этаж.Ряд Set start)
                this.fРяд = value;
                // *** Start programmer edit section *** (Этаж.Ряд Set end)

                // *** End programmer edit section *** (Этаж.Ряд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЭтажE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭтажE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭтажE", typeof(IIS.Cursed.Этаж));
                }
            }
            
            /// <summary>
            /// "ЭтажL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЭтажL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЭтажL", typeof(IIS.Cursed.Этаж));
                }
            }
        }
    }
}
