//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Cursed
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ячейка.
    /// </summary>
    // *** Start programmer edit section *** (Ячейка CustomAttributes)

    // *** End programmer edit section *** (Ячейка CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЯчейкаE", new string[] {
            "НомерЯчейки as \'Номер ячейки\'",
            "Этаж as \'Этаж\'",
            "Этаж.НомерЭтажа as \'Номер этажа\'"}, Hidden=new string[] {
            "Этаж.НомерЭтажа"})]
    [MasterViewDefineAttribute("ЯчейкаE", "Этаж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерЭтажа")]
    [View("ЯчейкаL", new string[] {
            "НомерЯчейки as \'Номер ячейки\'",
            "Этаж.НомерЭтажа as \'Номер этажа\'"})]
    public class Ячейка : ICSSoft.STORMNET.DataObject
    {
        
        private string fНомерЯчейки;
        
        private IIS.Cursed.Этаж fЭтаж;
        
        // *** Start programmer edit section *** (Ячейка CustomMembers)

        // *** End programmer edit section *** (Ячейка CustomMembers)

        
        /// <summary>
        /// НомерЯчейки.
        /// </summary>
        // *** Start programmer edit section *** (Ячейка.НомерЯчейки CustomAttributes)

        // *** End programmer edit section *** (Ячейка.НомерЯчейки CustomAttributes)
        [StrLen(255)]
        public virtual string НомерЯчейки
        {
            get
            {
                // *** Start programmer edit section *** (Ячейка.НомерЯчейки Get start)

                // *** End programmer edit section *** (Ячейка.НомерЯчейки Get start)
                string result = this.fНомерЯчейки;
                // *** Start programmer edit section *** (Ячейка.НомерЯчейки Get end)

                // *** End programmer edit section *** (Ячейка.НомерЯчейки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ячейка.НомерЯчейки Set start)

                // *** End programmer edit section *** (Ячейка.НомерЯчейки Set start)
                this.fНомерЯчейки = value;
                // *** Start programmer edit section *** (Ячейка.НомерЯчейки Set end)

                // *** End programmer edit section *** (Ячейка.НомерЯчейки Set end)
            }
        }
        
        /// <summary>
        /// Ячейка.
        /// </summary>
        // *** Start programmer edit section *** (Ячейка.Этаж CustomAttributes)

        // *** End programmer edit section *** (Ячейка.Этаж CustomAttributes)
        [PropertyStorage(new string[] {
                "Этаж"})]
        [NotNull()]
        public virtual IIS.Cursed.Этаж Этаж
        {
            get
            {
                // *** Start programmer edit section *** (Ячейка.Этаж Get start)

                // *** End programmer edit section *** (Ячейка.Этаж Get start)
                IIS.Cursed.Этаж result = this.fЭтаж;
                // *** Start programmer edit section *** (Ячейка.Этаж Get end)

                // *** End programmer edit section *** (Ячейка.Этаж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Ячейка.Этаж Set start)

                // *** End programmer edit section *** (Ячейка.Этаж Set start)
                this.fЭтаж = value;
                // *** Start programmer edit section *** (Ячейка.Этаж Set end)

                // *** End programmer edit section *** (Ячейка.Этаж Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЯчейкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЯчейкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЯчейкаE", typeof(IIS.Cursed.Ячейка));
                }
            }
            
            /// <summary>
            /// "ЯчейкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЯчейкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЯчейкаL", typeof(IIS.Cursed.Ячейка));
                }
            }
        }
    }
}
